{"name": "test_add1[get_data0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 2\n  +3\n  -2", "trace": "self = <testing.test_calc_fixture_param.TestCalc object at 0x0000000003BB1448>\nget_cacl = <pythoncode.calculator.Calculator object at 0x0000000003BA9CC8>\nget_data = [1, 1, 3]\n\n    @pytest.mark.add\n    @pytest.mark.P0\n    # @pytest.mark.parametrize(\"a,b,expect\", [[1, 1, 3], [-0.01, 0.02, 0.01], [10, 0.02, 10.02]])\n    # def test_add1(self, get_cacl, a, b, expect):\n    def test_add1(self, get_cacl,get_data):\n        \"\"\"\n        【正向】P0 :2个整数相加，结果计算正确\n        :return:\n        \"\"\"\n        logging.info(\"加法用例P0级别\")\n        logging.info(f'输入数据：{get_data[0],get_data[1]}，预期数据：{get_data[2]}')\n        result = get_cacl.add(get_data[0], get_data[1])\n>       assert get_data[2] == result\nE       assert 3 == 2\nE         +3\nE         -2\n\ntest_calc_fixture_param.py:37: AssertionError"}, "description": "\n        【正向】P0 :2个整数相加，结果计算正确\n        :return:\n        ", "attachments": [{"name": "log", "source": "d083f148-7e68-41b9-824c-b679217b4041-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_data", "value": "[1, 1, 3]"}], "start": 1644926027298, "stop": 1644926027299, "uuid": "76663eab-d104-4c0e-9f26-c59cac68ae56", "historyId": "fe0d2d745875f10505369227fa62d4d4", "testCaseId": "0f0722539eb4329851b1e5196b2e2f85", "fullName": "testing.test_calc_fixture_param.TestCalc#test_add1", "labels": [{"name": "tag", "value": "add"}, {"name": "tag", "value": "P0"}, {"name": "parentSuite", "value": "testing"}, {"name": "suite", "value": "test_calc_fixture_param"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "zenghuan-PC"}, {"name": "thread", "value": "12672-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testing.test_calc_fixture_param"}]}