{"name": "test_add3[99.01-0-参数大小超出范围]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/Users/juanxu/Downloads/logo.jpg'", "trace": "self = <testing.test_calc_fixture_param.TestCalc object at 0x000000000394DAC8>, get_cacl = <pythoncode.calculator.Calculator object at 0x000000000396E688>, a = 99.01, b = 0\nexpect = '参数大小超出范围'\n\n    @pytest.mark.add\n    @pytest.mark.P1_2\n    @pytest.mark.parametrize(\"a,b,expect\", [\n        [99.01, 0, \"参数大小超出范围\"],\n        [-99.01, -1, \"参数大小超出范围\"],\n        [2, 99.01, \"参数大小超出范围\"],\n        [1, -99.01, \"参数大小超出范围\"]\n    ])\n    @pytest.mark.run(order=2)\n    @allure.story('p1_2测试用例')\n    def test_add3(self, get_cacl, a, b, expect):\n        \"\"\"\n        【边界】P1:无效边界值相加，给出提示信息\n        :return:\n        \"\"\"\n        logging.info(\"加法用例P1_2级别\")\n        logging.info(f'输入数据：{a, b}，预期数据：{expect}')\n        with allure.step(\"步骤一：执行相加操作\"):\n            result = get_cacl.add(a, b)\n        # 断言\n        with allure.step(\"步骤二：断言\"):\n            allure.attach.file(\"/Users/juanxu/Downloads/logo.jpg\",\n                               name=\"图片\",\n                               attachment_type=allure.attachment_type.JPG,\n>                              extension=\".jpg\")\n\ntest_calc_fixture_param.py:87: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nd:\\program files (x86)\\python379\\lib\\site-packages\\allure_commons\\_allure.py:182: in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\nd:\\program files (x86)\\python379\\lib\\site-packages\\pluggy\\_hooks.py:265: in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\nd:\\program files (x86)\\python379\\lib\\site-packages\\pluggy\\_manager.py:80: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\nd:\\program files (x86)\\python379\\lib\\site-packages\\allure_pytest\\listener.py:226: in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\nd:\\program files (x86)\\python379\\lib\\site-packages\\allure_commons\\reporter.py:114: in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\nd:\\program files (x86)\\python379\\lib\\site-packages\\pluggy\\_hooks.py:265: in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\nd:\\program files (x86)\\python379\\lib\\site-packages\\pluggy\\_manager.py:80: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\nd:\\program files (x86)\\python379\\lib\\site-packages\\allure_commons\\logger.py:53: in report_attached_file\n    shutil.copy2(source, destination)\nd:\\program files (x86)\\python379\\lib\\shutil.py:266: in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nsrc = '/Users/juanxu/Downloads/logo.jpg', dst = 'C:\\\\Users\\\\zenghuan\\\\PycharmProjects\\\\ck22_20220113\\\\testing\\\\result\\\\1\\\\ede71271-f87f-451e-8994-9b1d8a472a70-attachment.jpg'\n\n    def copyfile(src, dst, *, follow_symlinks=True):\n        \"\"\"Copy data from src to dst.\n    \n        If follow_symlinks is not set and src is a symbolic link, a new\n        symlink will be created instead of copying the file it points to.\n    \n        \"\"\"\n        if _samefile(src, dst):\n            raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\n    \n        for fn in [src, dst]:\n            try:\n                st = os.stat(fn)\n            except OSError:\n                # File most likely does not exist\n                pass\n            else:\n                # XXX What about other special files? (sockets, devices...)\n                if stat.S_ISFIFO(st.st_mode):\n                    raise SpecialFileError(\"`%s` is a named pipe\" % fn)\n    \n        if not follow_symlinks and os.path.islink(src):\n            os.symlink(os.readlink(src), dst)\n        else:\n>           with open(src, 'rb') as fsrc:\nE           FileNotFoundError: [Errno 2] No such file or directory: '/Users/juanxu/Downloads/logo.jpg'\n\nd:\\program files (x86)\\python379\\lib\\shutil.py:120: FileNotFoundError"}, "description": "\n        【边界】P1:无效边界值相加，给出提示信息\n        :return:\n        ", "steps": [{"name": "步骤一：执行相加操作", "status": "passed", "start": 1645096470245, "stop": 1645096470245}, {"name": "步骤二：断言", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/Users/juanxu/Downloads/logo.jpg'\n", "trace": "  File \"C:\\Users\\zenghuan\\PycharmProjects\\ck22_20220113\\testing\\test_calc_fixture_param.py\", line 87, in test_add3\n    extension=\".jpg\")\n  File \"d:\\program files (x86)\\python379\\lib\\site-packages\\allure_commons\\_allure.py\", line 182, in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"d:\\program files (x86)\\python379\\lib\\site-packages\\pluggy\\_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"d:\\program files (x86)\\python379\\lib\\site-packages\\pluggy\\_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"d:\\program files (x86)\\python379\\lib\\site-packages\\pluggy\\_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"d:\\program files (x86)\\python379\\lib\\site-packages\\pluggy\\_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"d:\\program files (x86)\\python379\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\program files (x86)\\python379\\lib\\site-packages\\allure_pytest\\listener.py\", line 226, in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"d:\\program files (x86)\\python379\\lib\\site-packages\\allure_commons\\reporter.py\", line 114, in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n  File \"d:\\program files (x86)\\python379\\lib\\site-packages\\pluggy\\_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"d:\\program files (x86)\\python379\\lib\\site-packages\\pluggy\\_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"d:\\program files (x86)\\python379\\lib\\site-packages\\pluggy\\_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"d:\\program files (x86)\\python379\\lib\\site-packages\\pluggy\\_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"d:\\program files (x86)\\python379\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\program files (x86)\\python379\\lib\\site-packages\\allure_commons\\logger.py\", line 53, in report_attached_file\n    shutil.copy2(source, destination)\n  File \"d:\\program files (x86)\\python379\\lib\\shutil.py\", line 266, in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n  File \"d:\\program files (x86)\\python379\\lib\\shutil.py\", line 120, in copyfile\n    with open(src, 'rb') as fsrc:\n"}, "attachments": [{"name": "图片", "source": "ede71271-f87f-451e-8994-9b1d8a472a70-attachment.jpg", "type": "image/jpg"}], "start": 1645096470245, "stop": 1645096470245}], "attachments": [{"name": "log", "source": "90940dec-0b7d-4f54-ae60-85f96b1706c1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "99.01"}, {"name": "b", "value": "0"}, {"name": "expect", "value": "'参数大小超出范围'"}], "start": 1645096470244, "stop": 1645096470248, "uuid": "fa4a9499-8897-4de2-afdb-3b7d5bafa9cb", "historyId": "c8f09ff56ce3e7ac9c21d6e28ba31da5", "testCaseId": "e868e717891580775a3d179b88f173ed", "fullName": "testing.test_calc_fixture_param.TestCalc#test_add3", "labels": [{"name": "feature", "value": "计算器测试用例"}, {"name": "story", "value": "p1_2测试用例"}, {"name": "tag", "value": "add"}, {"name": "tag", "value": "run(order=2)"}, {"name": "tag", "value": "P1_2"}, {"name": "parentSuite", "value": "testing"}, {"name": "suite", "value": "test_calc_fixture_param"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "zenghuan-PC"}, {"name": "thread", "value": "14748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testing.test_calc_fixture_param"}]}